//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPF_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Info
    {
        public int ClientID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string HomeNumber { get; set; }
        public string Email { get; set; }
        public string StreetAddress { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public short PostalCode { get; set; }
        public string Gender { get; set; }
        public string ClientType { get; set; }
        public string Location { get; set; }
        public System.DateTime SignUpDate { get; set; }
    }
}
